### ISSUE TITLE
on copy-paste a space is added to the begin of the value

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/Centre-Registry#11]
Experienced on MacOS, Firefox 49.0 - everytime I paste a value (eg from the drupal registration form), a preceding space is added

**Comment by sanmai-NL** [comment]
I cannot reproduce that problem with Chromium 53.0.2785.143 (64-bit) and 49.0.1 on Linux. I am not copying anything from a Drupal form, however. Please check copying and pasting elsewhere. It is unlikely Django would add such a space.

**Comment by sanmai-NL** [comment]
@dietervu: check later whether this issue was solved with 2.2.0 and reopen if not, please. The admin theme was changed back to the default, and is more current as result, so this is perhaps fixed.
