### ISSUE TITLE
Add suport for OAI-PMH sets

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/Centre-Registry#15]
Right now there is only support to specifiy a single OAI-PMH endpoint per centre. We should (optionally) support a set of sets (strings) per OAI-PMH endpoint. Would be useful to enable selective harvesting (like eg for TrolLING or B2SHARE).

**Comment by andmor-** [comment]
Implemented in 2.3.0. See https://centres-staging.clarin.eu

**Comment by twagoo** [comment]
Adoption of this solution on the harvest manager end covered by https://github.com/clarin-eric/oai-harvest-manager/issues/26

**Comment by andmor-** [comment]
Fixed in [2.3.0](../releases/tag/2.3.0)
