### ISSUE TITLE
Show orphan contacts in admin view

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/Centre-Registry#23]
Would be useful to have an option to quickly filter for contacts that are not connected to any centre, so that we can go though the list from time to time and clean it up.

**Comment by andmor-** [comment]
@MichalGawor can you evaluate how difficult this would be?

**Comment by MichalGawor** [comment]
On hold for now. To be addressed after upgrade to django-2.2.7 is finished.

**Comment by andmor-** [comment]
Implemented in 2.3.0. See https://centres-staging.clarin.eu
