### ISSUE TITLE
EduPersonPrincipalName may be NULL

### ISSUE THREAD

**Issue by sanmai-NL** [clarin-eric/Centre-Registry#6]

**Comment by sanmai-NL** [comment]
See https://code.djangoproject.com/ticket/4136

**Comment by dietervu** [comment]
Issue in django seems to be fixed 3 months ago: https://code.djangoproject.com/ticket/4136#comment:42

**Comment by sanmai-NL** [comment]
@dietervu: check later whether this issue was solved with 2.2.0 and reopen if not, please. It uses Django 1.9.10 instead of 1.8.x, so this is perhaps fixed.
