### ISSUE TITLE
After creating a contact person, a white screen is shown, centre form data is lost

### ISSUE THREAD

**Issue by dietervu** [clarin-eric/Centre-Registry#7]
Workflow (Firefox 47.0, MacOS 10.9.5):
- create a new centre
- then inside the partially filled form, create a new contact person, this opens in the same tab (hiding the centre form)
- when that person is successfully added,a white screen is shown and the person is registered but the centre info is lost

**Comment by sanmai-NL** [comment]
Confirmed the white screen. Allowing popups from `*.clarin.eu` does not seem to help. The centre form wasn't lost in Chromium 51.0.2704.84 (64-bit) after I clicked the browser back button two times, however.

**Comment by sanmai-NL** [comment]
@dietervu: check later whether this issue was solved with 2.2.0 and reopen if not, please. The admin theme was changed back to the default, and is more current as result, so this is perhaps fixed.

**Comment by andmor-** [comment]
This seems resolved. Will reopen if not
